### ISSUE TITLE
Error in parse method

### ISSUE THREAD

**Issue by freeart** [scarney81/pg-hstore#17]
I found an error in regexp
var hstore = require('pg-hstore')({ sanitize: true });
var obj = {"description": "\\", "manufacturer": "Fair-Rite"};
var hstore = hstore.stringify(obj);
var objagain = hstore.parse(hstore); //error

**Comment by gigablah** [comment]
#18 solved this issue for me, although it was not merged. `2.2.0` still has the error.

**Comment by scarney81** [comment]
Not entirely sure how that fix was dropped. It's been re-added and pub'd: 2.3.2
